# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c677db936a2938ab2b74f76c960073f6e3c61f8551a13afc7718d5e5c51da8b5b14a2b8fc1f5dd4d30ea44902aaa1664066efa3817ebebe3b487ee1adfcfdb1a

test:
  secret_key_base: 004e1b084c489e0fcb7c16be1b2e1c0d00d41b36fc6615d9387053731fa7813980ebc16984c3d2db13fbfe11fa412ca23b7d89aca909a72ca1732cae4d53712c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
